packages:
  - "apps/*"
  - "packages/*"
  - "plugins/*"

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - sharp
  - "@prisma/client"
  - prisma
  - unrs-resolver
  - "@prisma/engines"
  - "@prisma/client"
  - "@nestjs/core"
