import { NextResponse } from 'next/server';
import { createImageProvider, listImageProviders } from '@opendesign/ai';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Image generation endpoint.
 *
 * Returns **base64**, not a URL, and does not persist anything. Ingestion
 * happens on the client so generated bytes go through the same storage adapter
 * as an upload — which is what keeps the local-first path intact: with inline
 * storage the image never touches a server disk at all.
 *
 * Local providers are exempt from the key check because they have no key; the
 * request still routes through here so a self-hosted deployment can reach an
 * image server on its own network.
 *
 * Keys resolve the same way as in `/api/ai`: the user's own key from Settings
 * first, then a server environment variable.
 */

const ENV_KEYS: Record<string, string> = {
  'openai-images': 'OPENAI_API_KEY',
  'google-images': 'GOOGLE_API_KEY',
};

const KEY_HEADER = 'x-od-api-key';
const BASE_URL_HEADER = 'x-od-base-url';

interface GenerateBody {
  prompt: string;
  providerId: string;
  model: string;
  size?: string;
  count?: number;
  negativePrompt?: string;
}

export async function GET() {
  return NextResponse.json({
    providers: listImageProviders().map((provider) => ({
      ...provider,
      configured:
        provider.locality === 'local' || Boolean(process.env[ENV_KEYS[provider.id] ?? '']),
    })),
  });
}

export async function POST(request: Request) {
  let body: GenerateBody;
  try {
    body = (await request.json()) as GenerateBody;
  } catch {
    return NextResponse.json({ error: 'invalid JSON body' }, { status: 400 });
  }

  if (!body.prompt?.trim()) {
    return NextResponse.json({ error: 'prompt is required' }, { status: 400 });
  }

  const envKey = ENV_KEYS[body.providerId];
  const apiKey =
    request.headers.get(KEY_HEADER)?.trim() || (envKey ? process.env[envKey] : undefined);
  const baseUrl = request.headers.get(BASE_URL_HEADER)?.trim();

  if (envKey && !apiKey) {
    return NextResponse.json(
      {
        error: `no API key for ${body.providerId}`,
        hint: 'Add your key in Settings, or run a local image server and select it instead.',
      },
      { status: 401 },
    );
  }

  let provider;
  try {
    provider = createImageProvider(body.providerId, {
      ...(apiKey ? { apiKey } : {}),
      ...(baseUrl ? { baseUrl } : {}),
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'unknown image provider' },
      { status: 400 },
    );
  }

  try {
    const images = await provider.generate({
      prompt: body.prompt,
      model: body.model,
      ...(body.size ? { size: body.size } : {}),
      ...(body.count ? { count: Math.min(body.count, 4) } : {}),
      ...(body.negativePrompt ? { negativePrompt: body.negativePrompt } : {}),
      signal: request.signal,
    });

    return NextResponse.json({ images });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 502 },
    );
  }
}
