import { NextResponse } from 'next/server';
import { createImageProvider, listImageProviders } from '@opendesign/ai';
import { CredentialError, providerSignal, resolveCredentials } from '@/lib/provider-credentials';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Image generation endpoint.
 *
 * Returns **base64**, not a URL, and does not persist anything. Ingestion
 * happens on the client so generated bytes go through the same storage adapter
 * as an upload — which is what keeps the local-first path intact: with inline
 * storage the image never touches a server disk at all.
 *
 * Local providers are exempt from the key check because they have no key; the
 * request still routes through here so a self-hosted deployment can reach an
 * image server on its own network.
 *
 * Keys resolve the same way as in `/api/ai`: the user's own key from Settings
 * first, then a server environment variable.
 */

const ENV_KEYS: Record<string, string> = {
  'openai-images': 'OPENAI_API_KEY',
  'google-images': 'GOOGLE_API_KEY',
};

interface GenerateBody {
  prompt: string;
  providerId: string;
  model: string;
  size?: string;
  count?: number;
  negativePrompt?: string;
}

export async function GET() {
  return NextResponse.json({
    providers: listImageProviders().map((provider) => ({
      ...provider,
      configured:
        provider.locality === 'local' || Boolean(process.env[ENV_KEYS[provider.id] ?? '']),
    })),
  });
}

export async function POST(request: Request) {
  let body: GenerateBody;
  try {
    body = (await request.json()) as GenerateBody;
  } catch {
    return NextResponse.json({ error: 'corpo JSON inválido' }, { status: 400 });
  }

  if (!body.prompt?.trim()) {
    return NextResponse.json({ error: 'o prompt é obrigatório' }, { status: 400 });
  }

  if (!body.model?.trim()) {
    return NextResponse.json({ error: 'o modelo é obrigatório' }, { status: 400 });
  }

  const envKey = ENV_KEYS[body.providerId];
  const locality =
    listImageProviders().find((provider) => provider.id === body.providerId)?.locality ?? 'cloud';

  let apiKey: string | undefined;
  let baseUrl: string | undefined;
  try {
    ({ apiKey, baseUrl } = await resolveCredentials({
      headers: request.headers,
      envKey,
      locality,
    }));
  } catch (error) {
    if (error instanceof CredentialError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    throw error;
  }

  if (envKey && !apiKey) {
    return NextResponse.json(
      {
        error: `sem chave de API para ${body.providerId}`,
        hint: 'Adicione sua chave em Ajustes, ou rode um servidor de imagens local e selecione-o.',
      },
      { status: 401 },
    );
  }

  let provider;
  try {
    provider = createImageProvider(body.providerId, {
      ...(apiKey ? { apiKey } : {}),
      ...(baseUrl ? { baseUrl } : {}),
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'provedor de imagens desconhecido' },
      { status: 400 },
    );
  }

  try {
    const images = await provider.generate({
      prompt: body.prompt,
      model: body.model,
      ...(body.size ? { size: body.size } : {}),
      // Clamped at both ends: the ceiling is what the deployment is willing to
      // pay for, and the floor is because a provider handed `n: -5` answers
      // with something unhelpful rather than an error.
      ...(body.count ? { count: Math.max(1, Math.min(Math.floor(body.count), 4)) } : {}),
      ...(body.negativePrompt ? { negativePrompt: body.negativePrompt } : {}),
      signal: providerSignal(request),
    });

    return NextResponse.json({ images });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : String(error) },
      { status: 502 },
    );
  }
}
